#!/usr/bin/env python3
"""Find candidate papers for a MIPLIB instance group via OpenAlex.

Produces a markdown draft (matching the mipviz notes template) listing
candidate references for a given group or instance name. Intended as a
triage starting point — a human reviews, keeps the relevant entries,
and writes the final note by hand.

Usage:
    python scripts/find_group_references.py markshare
    python scripts/find_group_references.py markshare --query "markshare Bixby LLL"
    python scripts/find_group_references.py markshare --limit 30 > draft.md
"""

import argparse
import json
import sys
import time
import urllib.error
import urllib.parse
import urllib.request

API_BASE = "https://api.openalex.org/works"
# OpenAlex asks that scripts include a mailto in the User-Agent for the
# polite pool (higher rate limits). Override with --email to use your own.
DEFAULT_EMAIL = "mipviz@example.com"


def search(query, limit=20, email=DEFAULT_EMAIL):
    params = urllib.parse.urlencode({
        "search": query,
        "per-page": min(limit, 25),
        "mailto": email,
    })
    url = f"{API_BASE}?{params}"
    req = urllib.request.Request(url, headers={
        "User-Agent": f"mipviz-reference-finder/0.1 (mailto:{email})",
    })
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            return json.loads(r.read())
    except urllib.error.HTTPError as e:
        if e.code == 429:
            print("Rate limited by OpenAlex; retrying in 10s...", file=sys.stderr)
            time.sleep(10)
            with urllib.request.urlopen(req, timeout=30) as r:
                return json.loads(r.read())
        raise


def reconstruct_abstract(inverted_index):
    """OpenAlex returns abstracts as an inverted index {word: [positions]}."""
    if not inverted_index:
        return ""
    words_at = {}
    for word, positions in inverted_index.items():
        for p in positions:
            words_at[p] = word
    return " ".join(words_at[i] for i in sorted(words_at))


def format_authors(authorships, max_authors=3):
    if not authorships:
        return "—"
    names = [
        (a.get("author") or {}).get("display_name", "?")
        for a in authorships[:max_authors]
    ]
    out = ", ".join(names)
    if len(authorships) > max_authors:
        out += " et al."
    return out


def get_venue(work):
    loc = work.get("primary_location") or {}
    source = loc.get("source") or {}
    return source.get("display_name") or ""


def draft_markdown(group, query, results):
    papers = results.get("results") or []
    lines = []
    lines.append(f"# {group}")
    lines.append("")
    lines.append("<!-- Draft generated by scripts/find_group_references.py.")
    lines.append(f"     Query: {query}")
    lines.append(f"     Keep relevant entries, delete the rest, fill in the")
    lines.append(f"     Origin / Problem description / Techniques sections. -->")
    lines.append("")
    lines.append("## Origin")
    lines.append("")
    lines.append("TODO: one paragraph on where this group comes from and what the")
    lines.append("problem is.")
    lines.append("")
    lines.append("## Techniques that help")
    lines.append("")
    lines.append("TODO: bullet list of techniques, each with a citation.")
    lines.append("")
    lines.append("## Candidate references")
    lines.append("")
    if not papers:
        lines.append("_No results from OpenAlex for this query._")
        lines.append("")
    for p in papers:
        title = (p.get("title") or "Untitled").strip()
        authors = format_authors(p.get("authorships") or [])
        year = p.get("publication_year") or "—"
        venue = get_venue(p).strip()
        cites = p.get("cited_by_count")
        doi = p.get("doi")
        # DOI may come back as a full URL
        if doi and doi.startswith("https://doi.org/"):
            doi = doi[len("https://doi.org/"):]
        abstract = reconstruct_abstract(p.get("abstract_inverted_index")).strip()
        if len(abstract) > 320:
            abstract = abstract[:320].rsplit(" ", 1)[0] + "…"

        lines.append(f"### {title}")
        meta_bits = [authors, str(year)]
        if venue:
            meta_bits.append(venue)
        if cites is not None:
            meta_bits.append(f"{cites} cites")
        lines.append(f"_{' · '.join(meta_bits)}_")
        lines.append("")
        links = []
        if doi:
            links.append(f"[DOI](https://doi.org/{doi})")
        oa_id = p.get("id")
        if oa_id:
            links.append(f"[OpenAlex]({oa_id})")
        if links:
            lines.append(" · ".join(links))
            lines.append("")
        if abstract:
            lines.append(f"> {abstract}")
            lines.append("")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("group", help="MIPLIB group name (or instance name)")
    ap.add_argument("--query", help="Override search query (default: '<group> MIPLIB integer programming')")
    ap.add_argument("--limit", type=int, default=20, help="Max papers to return (default 20)")
    ap.add_argument("--email", default=DEFAULT_EMAIL, help="Contact email for OpenAlex polite pool")
    args = ap.parse_args()

    query = args.query or f"{args.group} MIPLIB integer programming"
    print(f"Searching OpenAlex: {query}", file=sys.stderr)
    results = search(query, limit=args.limit, email=args.email)
    n = len(results.get("results") or [])
    print(f"Got {n} candidate papers", file=sys.stderr)
    print(draft_markdown(args.group, query, results))


if __name__ == "__main__":
    main()
